const U='https://pnisrktkkbzspolkfkag.supabase.co';
const K='sb_publishable_ClLcjnxymypzS2O6x1TzwA_c9y7-j1Y';
const LS='banking_engine_session_v2';
const S={session:null,user:null,role:null,segments:[],categories:[],calculators:[],versions:[],selectedCalculator:null,selectedVersion:null};
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function notice(el,msg,type='info'){el.hidden=false;el.textContent=msg;el.className=`notice ${type}`}
function saveSession(x){S.session=x;localStorage.setItem(LS,JSON.stringify(x))}
function clearSession(){S.session=null;S.user=null;S.role=null;localStorage.removeItem(LS)}
function authHeaders(json=true){return {apikey:K, ...(S.session?.access_token?{Authorization:`Bearer ${S.session.access_token}`}:{Authorization:`Bearer ${K}`}), ...(json?{'Content-Type':'application/json'}:{})}}
async function api(url,opt={}){let r=await fetch(U+url,{...opt,headers:{...authHeaders(),...(opt.headers||{})}});if(r.status===401&&S.session?.refresh_token){const ok=await refreshSession();if(ok)r=await fetch(U+url,{...opt,headers:{...authHeaders(),...(opt.headers||{})}})}if(!r.ok)throw Error((await r.text())||`${r.status}`);if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
async function refreshSession(){try{const r=await fetch(`${U}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:K,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:S.session.refresh_token})});if(!r.ok)return false;saveSession(await r.json());return true}catch{return false}}
async function auth(mode,email,password){const endpoint=mode==='signup'?'/auth/v1/signup':'/auth/v1/token?grant_type=password';const r=await fetch(U+endpoint,{method:'POST',headers:{apikey:K,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw Error(d.msg||d.error_description||d.message||'Auth gagal');if(mode==='signup'&&!d.access_token)return {signupPending:true};saveSession(d);return d}
async function getUser(){const r=await fetch(U+'/auth/v1/user',{headers:authHeaders(false)});if(!r.ok)throw Error('Session tidak valid');S.user=await r.json();return S.user}
async function getRole(){const rows=await api(`/rest/v1/user_roles?select=role&user_id=eq.${S.user.id}`);S.role=rows?.[0]?.role||null;return S.role}
async function logout(){try{await fetch(U+'/auth/v1/logout',{method:'POST',headers:authHeaders(false)})}catch{}clearSession();location.reload()}

let authMode='login';
$$('[data-auth]').forEach(b=>b.onclick=()=>{$$('[data-auth]').forEach(x=>x.classList.toggle('active',x===b));authMode=b.dataset.auth;$('#authForm button').textContent=authMode==='login'?'Login':'Daftar'});
$('#authForm').onsubmit=async e=>{e.preventDefault();const m=$('#authMessage');m.hidden=true;try{const d=await auth(authMode,$('#authEmail').value.trim(),$('#authPassword').value);if(d.signupPending){notice(m,'Akun dibuat. Cek email bila email confirmation aktif, lalu login.','success');return}await boot()}catch(err){notice(m,err.message,'error')}};
$('#activationForm').onsubmit=async e=>{e.preventDefault();const m=$('#activationMessage');try{const ok=await api('/rest/v1/rpc/redeem_admin_code',{method:'POST',body:JSON.stringify({p_code:$('#activationCode').value.trim()})});if(!ok)throw Error('Activation code salah, sudah dipakai, atau kedaluwarsa.');await getRole();await showAdmin()}catch(err){notice(m,err.message,'error')}};
$('#activationLogout').onclick=logout; $('#logoutBtn').onclick=logout;

async function boot(){const raw=localStorage.getItem(LS);if(!S.session&&raw){try{S.session=JSON.parse(raw)}catch{}}if(!S.session){showGate('auth');return}try{await getUser();await getRole();if(S.role!=='admin'){showGate('activation');return}await showAdmin()}catch{clearSession();showGate('auth')}}
function showGate(which){$('#authGate').hidden=which!=='auth';$('#activationGate').hidden=which!=='activation';$('#adminApp').hidden=true}
async function showAdmin(){showGate('none');$('#authGate').hidden=true;$('#activationGate').hidden=true;$('#adminApp').hidden=false;$('#adminIdentity').textContent=`${S.user.email} · ADMIN`;await loadCore();renderAll()}

async function loadCore(){const [a,b,c,d]=await Promise.all([
 api('/rest/v1/segments?select=*&order=sort_order,name'),api('/rest/v1/calculator_categories?select=*&order=sort_order,name'),api('/rest/v1/calculators?select=*&order=sort_order,name'),api('/rest/v1/calculator_versions?select=*&order=created_at.desc')]);
 Object.assign(S,{segments:a,categories:b,calculators:c,versions:d});
 $('[data-stat="segments"]').textContent=a.length;$('[data-stat="calculators"]').textContent=c.length;$('[data-stat="drafts"]').textContent=d.filter(x=>x.status==='draft').length;
 try{const audit=await api('/rest/v1/audit_logs?select=id&limit=500');$('[data-stat="audit"]').textContent=audit.length}catch{$('[data-stat="audit"]').textContent='—'}
}
function renderAll(){renderSegmentsAdmin();renderCalculatorList()}

$$('.admin-nav').forEach(b=>b.onclick=()=>{$$('.admin-nav').forEach(x=>x.classList.toggle('active',x===b));$$('[data-view-panel]').forEach(p=>p.hidden=p.dataset.viewPanel!==b.dataset.view);if(b.dataset.view==='audit')loadAudit()});

function renderSegmentsAdmin(){const el=$('#segmentAdminList');if(!S.segments.length){el.innerHTML='<div class="editor-empty">Belum ada segment.</div>';return}el.innerHTML=S.segments.map(s=>{const cats=S.categories.filter(c=>c.segment_id===s.id);return `<article class="admin-row-card"><div class="admin-row-top"><div><b>${esc(s.name)}</b><div class="muted small">/${esc(s.slug)} · ${s.is_active?'Active':'Inactive'}</div></div><div><button class="tiny-btn" data-edit-segment="${s.id}">Edit</button><button class="tiny-btn" data-new-cat="${s.id}">+ Category</button></div></div><div class="chips">${cats.map(c=>`<span class="chip">${esc(c.name)} <button data-edit-cat="${c.id}">✎</button></span>`).join('')||'<span class="muted small">No category</span>'}</div></article>`}).join('');
 $$('[data-edit-segment]',el).forEach(b=>b.onclick=()=>segmentDialog(S.segments.find(x=>x.id===b.dataset.editSegment)));
 $$('[data-new-cat]',el).forEach(b=>b.onclick=()=>categoryDialog(null,b.dataset.newCat));
 $$('[data-edit-cat]',el).forEach(b=>b.onclick=()=>categoryDialog(S.categories.find(x=>x.id===b.dataset.editCat)));
}
$('#newSegmentBtn').onclick=()=>segmentDialog();
function openDialog(html){$('#genericDialogBody').innerHTML=html;$('#genericDialog').showModal()}
$('#genericClose').onclick=()=>$('#genericDialog').close();
function slugify(x){return x.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
function segmentDialog(s=null){openDialog(`<form id="entityForm" class="dialog-form"><div class="eyebrow">${s?'EDIT':'NEW'} SEGMENT</div><h2>${s?'Edit Segment':'Tambah Segment'}</h2><label>Name<input name="name" value="${esc(s?.name||'')}" required></label><label>Slug<input name="slug" value="${esc(s?.slug||'')}" required></label><label>Description<textarea name="description">${esc(s?.description||'')}</textarea></label><label>Sort Order<input name="sort_order" type="number" value="${s?.sort_order??0}"></label><label class="check"><input name="is_active" type="checkbox" ${s?.is_active!==false?'checked':''}> Active</label><button class="calculate-btn">Save</button></form>`);const f=$('#entityForm');f.name.oninput=()=>{if(!s||!f.slug.value)f.slug.value=slugify(f.name.value)};f.onsubmit=async e=>{e.preventDefault();const body={name:f.name.value.trim(),slug:f.slug.value.trim(),description:f.description.value.trim()||null,sort_order:Number(f.sort_order.value||0),is_active:f.is_active.checked,updated_at:new Date().toISOString()};await api('/rest/v1/segments'+(s?`?id=eq.${s.id}`:''),{method:s?'PATCH':'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});$('#genericDialog').close();await loadCore();renderAll()}}
function categoryDialog(c=null,segmentId=null){const sid=c?.segment_id||segmentId;openDialog(`<form id="entityForm" class="dialog-form"><div class="eyebrow">${c?'EDIT':'NEW'} CATEGORY</div><h2>${c?'Edit Category':'Tambah Category'}</h2><label>Segment<select name="segment_id">${S.segments.map(s=>`<option value="${s.id}" ${s.id===sid?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>Name<input name="name" value="${esc(c?.name||'')}" required></label><label>Slug<input name="slug" value="${esc(c?.slug||'')}" required></label><label>Sort Order<input name="sort_order" type="number" value="${c?.sort_order??0}"></label><label class="check"><input name="is_active" type="checkbox" ${c?.is_active!==false?'checked':''}> Active</label><button class="calculate-btn">Save</button></form>`);const f=$('#entityForm');f.name.oninput=()=>{if(!c||!f.slug.value)f.slug.value=slugify(f.name.value)};f.onsubmit=async e=>{e.preventDefault();const body={segment_id:f.segment_id.value,name:f.name.value.trim(),slug:f.slug.value.trim(),sort_order:Number(f.sort_order.value||0),is_active:f.is_active.checked,updated_at:new Date().toISOString()};await api('/rest/v1/calculator_categories'+(c?`?id=eq.${c.id}`:''),{method:c?'PATCH':'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});$('#genericDialog').close();await loadCore();renderAll()}}

function renderCalculatorList(){const el=$('#calculatorAdminList');el.innerHTML=S.calculators.map(c=>{const v=S.versions.find(x=>x.calculator_id===c.id);return `<button class="calc-admin-item ${S.selectedCalculator===c.id?'active':''}" data-calc="${c.id}"><b>${esc(c.name)}</b><span>${esc(c.status)} · v${esc(v?.version_no||'—')}</span></button>`}).join('')||'<div class="editor-empty">Belum ada calculator.</div>';$$('[data-calc]',el).forEach(b=>b.onclick=()=>selectCalculator(b.dataset.calc))}
$('#newCalculatorBtn').onclick=()=>calculatorDialog();
function calculatorDialog(){if(!S.categories.length){alert('Buat category dulu.');return}openDialog(`<form id="entityForm" class="dialog-form"><div class="eyebrow">NEW CALCULATOR</div><h2>Tambah Calculator</h2><label>Category<select name="category_id">${S.categories.map(c=>`<option value="${c.id}">${esc(S.segments.find(s=>s.id===c.segment_id)?.name||'')} · ${esc(c.name)}</option>`).join('')}</select></label><label>Name<input name="name" required></label><label>Slug<input name="slug" required></label><label>Short Description<textarea name="short_description"></textarea></label><label>Type<select name="calculation_type"><option>calculator</option><option>assessment</option><option>hybrid</option></select></label><label>Initial Version<input name="version_no" value="1.0" required></label><button class="calculate-btn">Create Draft</button></form>`);const f=$('#entityForm');f.name.oninput=()=>{if(!f.slug.value)f.slug.value=slugify(f.name.value)};f.onsubmit=async e=>{e.preventDefault();const [calc]=await api('/rest/v1/calculators',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({category_id:f.category_id.value,name:f.name.value.trim(),slug:f.slug.value.trim(),short_description:f.short_description.value.trim()||null,calculation_type:f.calculation_type.value,status:'draft'})});const [v]=await api('/rest/v1/calculator_versions',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({calculator_id:calc.id,version_no:f.version_no.value.trim(),status:'draft'})});$('#genericDialog').close();await loadCore();S.selectedCalculator=calc.id;S.selectedVersion=v.id;renderCalculatorList();await renderEditor()}}

async function selectCalculator(id){S.selectedCalculator=id;const versions=S.versions.filter(v=>v.calculator_id===id);S.selectedVersion=versions[0]?.id||null;renderCalculatorList();await renderEditor()}
async function renderEditor(){const c=S.calculators.find(x=>x.id===S.selectedCalculator);const el=$('#calculatorEditor');if(!c){el.className='editor-empty';el.innerHTML='Pilih calculator untuk mulai edit.';return}const versions=S.versions.filter(v=>v.calculator_id===c.id);const v=versions.find(x=>x.id===S.selectedVersion)||versions[0];S.selectedVersion=v?.id;let fields=[],formulas=[];if(v){[fields,formulas]=await Promise.all([api(`/rest/v1/calculator_fields?select=*&calculator_version_id=eq.${v.id}&order=sort_order`),api(`/rest/v1/calculator_formulas?select=*&calculator_version_id=eq.${v.id}&order=sort_order`)])}el.className='calculator-editor';el.innerHTML=`<div class="editor-head"><div><div class="eyebrow">CALCULATOR BUILDER</div><h2>${esc(c.name)}</h2><div class="muted">${esc(c.short_description||'')}</div></div><button class="tiny-btn" id="editCalcMeta">Edit Meta</button></div>
<div class="version-bar"><label>Version<select id="versionSelect">${versions.map(x=>`<option value="${x.id}" ${x.id===v?.id?'selected':''}>v${esc(x.version_no)} · ${esc(x.status)}</option>`).join('')}</select></label><button class="tiny-btn" id="cloneVersion">Clone Draft</button>${v?.status!=='published'?'<button class="primary-small" id="publishVersion">Publish</button>':''}</div>
<div class="builder-section"><div class="section-header"><div><h3>Input Fields</h3><p>Form public dibuat otomatis dari daftar ini.</p></div><button class="tiny-btn" id="addField">+ Field</button></div><div>${fields.map(f=>`<div class="builder-row"><div><b>${esc(f.label)}</b><span>${esc(f.field_key)} · ${esc(f.field_type)}</span></div><div><button class="tiny-btn" data-field="${f.id}">Edit</button><button class="danger-tiny" data-del-field="${f.id}">Delete</button></div></div>`).join('')||'<div class="muted small">Belum ada field.</div>'}</div></div>
<div class="builder-section"><div class="section-header"><div><h3>Formulas</h3><p>Diproses berurutan sesuai sort order.</p></div><button class="tiny-btn" id="addFormula">+ Formula</button></div><div>${formulas.map(f=>`<div class="builder-row"><div><b>${esc(f.label)}</b><span>${esc(f.formula_key)} = ${esc(f.expression)}</span></div><div><button class="tiny-btn" data-formula="${f.id}">Edit</button><button class="danger-tiny" data-del-formula="${f.id}">Delete</button></div></div>`).join('')||'<div class="muted small">Belum ada formula.</div>'}</div></div>
<div class="builder-section"><div class="section-header"><div><h3>Preview</h3><p>Test draft sebelum publish.</p></div><button class="tiny-btn" id="runPreview">Open Preview</button></div></div>`;
 $('#versionSelect').onchange=e=>{S.selectedVersion=e.target.value;renderEditor()};$('#editCalcMeta').onclick=()=>editCalculatorMeta(c);$('#cloneVersion').onclick=()=>cloneVersion(c);if($('#publishVersion'))$('#publishVersion').onclick=()=>publishVersion(v);$('#addField').onclick=()=>fieldDialog(null,v);$('#addFormula').onclick=()=>formulaDialog(null,v);$$('[data-field]',el).forEach(b=>b.onclick=()=>fieldDialog(fields.find(x=>x.id===b.dataset.field),v));$$('[data-formula]',el).forEach(b=>b.onclick=()=>formulaDialog(formulas.find(x=>x.id===b.dataset.formula),v));$$('[data-del-field]',el).forEach(b=>b.onclick=()=>deleteEntity('calculator_fields',b.dataset.delField));$$('[data-del-formula]',el).forEach(b=>b.onclick=()=>deleteEntity('calculator_formulas',b.dataset.delFormula));$('#runPreview').onclick=()=>previewDialog(c,v,fields,formulas)}

function editCalculatorMeta(c){openDialog(`<form id="entityForm" class="dialog-form"><h2>Edit Calculator</h2><label>Name<input name="name" value="${esc(c.name)}" required></label><label>Category<select name="category_id">${S.categories.map(x=>`<option value="${x.id}" ${x.id===c.category_id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label>Short Description<textarea name="short_description">${esc(c.short_description||'')}</textarea></label><label>Long Description<textarea name="long_description">${esc(c.long_description||'')}</textarea></label><button class="calculate-btn">Save</button></form>`);const f=$('#entityForm');f.onsubmit=async e=>{e.preventDefault();await api(`/rest/v1/calculators?id=eq.${c.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({name:f.name.value.trim(),category_id:f.category_id.value,short_description:f.short_description.value.trim()||null,long_description:f.long_description.value.trim()||null,updated_at:new Date().toISOString()})});$('#genericDialog').close();await loadCore();renderCalculatorList();renderEditor()}}
async function cloneVersion(c){const no=prompt('Nomor versi draft baru (contoh 1.1):');if(!no)return;const date=prompt('Effective from (YYYY-MM-DD), boleh kosong:','');const id=await api('/rest/v1/rpc/clone_calculator_version',{method:'POST',body:JSON.stringify({p_calculator_id:c.id,p_version_no:no,p_effective_from:date||null})});await loadCore();S.selectedVersion=id;renderCalculatorList();renderEditor()}
async function publishVersion(v){if(!v)return;const date=prompt('Publish effective from (YYYY-MM-DD):',new Date().toISOString().slice(0,10));if(!date)return;if(!confirm(`Publish v${v.version_no} efektif ${date}? Versi published sebelumnya akan dipensiunkan sesuai tanggal efektif.`))return;await api('/rest/v1/rpc/publish_calculator_version',{method:'POST',body:JSON.stringify({p_version_id:v.id,p_effective_from:date})});await loadCore();renderCalculatorList();renderEditor()}
async function deleteEntity(table,id){if(!confirm('Hapus item ini?'))return;await api(`/rest/v1/${table}?id=eq.${id}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});await renderEditor();await loadCore()}
function fieldDialog(f=null,v){if(!v)return alert('Buat version dulu.');openDialog(`<form id="entityForm" class="dialog-form"><h2>${f?'Edit':'Tambah'} Field</h2><label>Field Key<input name="field_key" value="${esc(f?.field_key||'')}" required pattern="[A-Za-z_][A-Za-z0-9_]*"></label><label>Label<input name="label" value="${esc(f?.label||'')}" required></label><label>Type<select name="field_type">${['number','currency','percentage','integer','select','date','boolean','text'].map(x=>`<option ${x===f?.field_type?'selected':''}>${x}</option>`).join('')}</select></label><label>Description<textarea name="description">${esc(f?.description||'')}</textarea></label><label>Default Value<input name="default_value" value="${f?.default_value??''}"></label><label>Min<input name="min" type="number" step="any" value="${f?.validation?.min??''}"></label><label>Max<input name="max" type="number" step="any" value="${f?.validation?.max??''}"></label><label>Sort Order<input name="sort_order" type="number" value="${f?.sort_order??0}"></label><label class="check"><input name="required" type="checkbox" ${f?.is_required!==false?'checked':''}> Required</label><button class="calculate-btn">Save</button></form>`);const form=$('#entityForm');form.onsubmit=async e=>{e.preventDefault();const dv=form.default_value.value;const validation={};if(form.min.value!=='')validation.min=Number(form.min.value);if(form.max.value!=='')validation.max=Number(form.max.value);let default_value=null;if(dv!=='')default_value=['number','currency','percentage','integer'].includes(form.field_type.value)?Number(dv):dv;const body={calculator_version_id:v.id,field_key:form.field_key.value.trim(),label:form.label.value.trim(),field_type:form.field_type.value,description:form.description.value.trim()||null,default_value,validation,is_required:form.required.checked,sort_order:Number(form.sort_order.value||0)};await api('/rest/v1/calculator_fields'+(f?`?id=eq.${f.id}`:''),{method:f?'PATCH':'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});$('#genericDialog').close();renderEditor()}}
function formulaDialog(f=null,v){if(!v)return;openDialog(`<form id="entityForm" class="dialog-form"><h2>${f?'Edit':'Tambah'} Formula</h2><label>Formula Key<input name="formula_key" value="${esc(f?.formula_key||'')}" required pattern="[A-Za-z_][A-Za-z0-9_]*"></label><label>Label<input name="label" value="${esc(f?.label||'')}" required></label><label>Expression<textarea name="expression" required placeholder="principal * annual_rate / 100">${esc(f?.expression||'')}</textarea></label><label>Output Type<select name="output_type">${['number','currency','percentage','integer','boolean','text'].map(x=>`<option ${x===f?.output_type?'selected':''}>${x}</option>`).join('')}</select></label><label>Precision<input name="precision_digits" type="number" value="${f?.precision_digits??0}"></label><label>Sort Order<input name="sort_order" type="number" value="${f?.sort_order??0}"></label><label>Explanation<textarea name="explanation_md">${esc(f?.explanation_md||'')}</textarea></label><label class="check"><input name="visible" type="checkbox" ${f?.is_visible!==false?'checked':''}> Visible result</label><button class="calculate-btn">Save</button></form>`);const form=$('#entityForm');form.onsubmit=async e=>{e.preventDefault();try{validateExpression(form.expression.value)}catch(err){alert('Formula invalid: '+err.message);return}const body={calculator_version_id:v.id,formula_key:form.formula_key.value.trim(),label:form.label.value.trim(),expression:form.expression.value.trim(),output_type:form.output_type.value,precision_digits:Number(form.precision_digits.value||0),sort_order:Number(form.sort_order.value||0),explanation_md:form.explanation_md.value.trim()||null,is_visible:form.visible.checked};await api('/rest/v1/calculator_formulas'+(f?`?id=eq.${f.id}`:''),{method:f?'PATCH':'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});$('#genericDialog').close();renderEditor()}}

function previewDialog(c,v,fields,formulas){openDialog(`<div class="preview-shell"><div class="eyebrow">PREVIEW · v${esc(v?.version_no||'')}</div><h2>${esc(c.name)}</h2><form id="previewForm" class="stack-form">${fields.map(f=>`<label>${esc(f.label)}<input name="${esc(f.field_key)}" type="${['currency','percentage','number','integer'].includes(f.field_type)?'number':'text'}" step="any" value="${f.default_value??''}" ${f.is_required?'required':''}></label>`).join('')}<button class="calculate-btn">Calculate Preview</button></form><div id="previewResults" class="preview-results"></div></div>`);$('#previewForm').onsubmit=e=>{e.preventDefault();const ctx={};fields.forEach(f=>ctx[f.field_key]=Number(e.target.elements[f.field_key].value||0));try{const rows=formulas.map(x=>{let value;if(x.formula_key==='monthly_payment'&&ctx.monthly_rate===0)value=ctx.principal/ctx.months;else value=evaluateExpression(x.expression,ctx);ctx[x.formula_key]=value;return {...x,value}});$('#previewResults').innerHTML=rows.filter(x=>x.is_visible!==false).map(x=>`<div class="result-item"><div class="result-label">${esc(x.label)}</div><div class="result-value">${formatValue(x.value,x.output_type,x.precision_digits)}</div></div>`).join('')}catch(err){$('#previewResults').innerHTML=`<div class="notice error">${esc(err.message)}</div>`}}}
function validateExpression(e){evaluateExpression(e,{principal:1,annual_rate:1,days:1,months:1,tax_rate:1,monthly_rate:1,gross_interest:1,tax_amount:1,monthly_payment:1,total_payment:1,total_interest:1,net_interest:1})}
function evaluateExpression(expr,context){const tokens=tokenize(expr),out=[],ops=[],prec={'+':1,'-':1,'*':2,'/':2,'^':3},right={'^':true};let prev='start';for(const t of tokens){if(t.type==='number'||t.type==='var'){out.push(t);prev='value';continue}if(t.value==='('){ops.push(t);prev='(';continue}if(t.value===')'){while(ops.length&&ops.at(-1).value!=='(')out.push(ops.pop());if(!ops.length)throw Error('Kurung tidak seimbang');ops.pop();prev='value';continue}if(t.type==='op'){if(t.value==='-'&&(prev==='start'||prev==='op'||prev==='('))out.push({type:'number',value:0});while(ops.length&&ops.at(-1).type==='op'&&(right[t.value]?prec[t.value]<prec[ops.at(-1).value]:prec[t.value]<=prec[ops.at(-1).value]))out.push(ops.pop());ops.push(t);prev='op'}}while(ops.length){if(ops.at(-1).value==='(')throw Error('Kurung tidak seimbang');out.push(ops.pop())}const st=[];for(const t of out){if(t.type==='number')st.push(Number(t.value));else if(t.type==='var'){if(!(t.value in context))throw Error(`Variable ${t.value} belum tersedia`);st.push(Number(context[t.value]))}else{const b=st.pop(),a=st.pop();if(a===undefined||b===undefined)throw Error('Ekspresi tidak valid');st.push(({'+':()=>a+b,'-':()=>a-b,'*':()=>a*b,'/':()=>a/b,'^':()=>a**b}[t.value])())}}if(st.length!==1||!Number.isFinite(st[0]))throw Error('Hasil formula tidak valid');return st[0]}
function tokenize(s){const out=[];let i=0;while(i<s.length){const c=s[i];if(/\s/.test(c)){i++;continue}if(/[0-9.]/.test(c)){let j=i+1;while(j<s.length&&/[0-9.]/.test(s[j]))j++;const v=s.slice(i,j);if((v.match(/\./g)||[]).length>1)throw Error('Angka tidak valid');out.push({type:'number',value:v});i=j;continue}if(/[A-Za-z_]/.test(c)){let j=i+1;while(j<s.length&&/[A-Za-z0-9_]/.test(s[j]))j++;out.push({type:'var',value:s.slice(i,j)});i=j;continue}if('+-*/^()'.includes(c)){out.push({type:'+-*/^'.includes(c)?'op':'paren',value:c});i++;continue}throw Error(`Karakter tidak diizinkan: ${c}`)}return out}
function formatValue(v,type,p=0){if(type==='currency')return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:p??0}).format(v);if(type==='percentage')return new Intl.NumberFormat('id-ID',{maximumFractionDigits:p??0}).format(v)+'%';return new Intl.NumberFormat('id-ID',{maximumFractionDigits:p??0}).format(v)}

async function loadAudit(){const el=$('#auditList');el.innerHTML='<div class="muted">Loading…</div>';try{const rows=await api('/rest/v1/audit_logs?select=*&order=created_at.desc&limit=100');$('[data-stat="audit"]').textContent=rows.length;el.innerHTML=rows.map(r=>`<article class="audit-row"><div><b>${esc(r.action)} · ${esc(r.entity_type)}</b><span>${esc(r.entity_id)}</span></div><time>${new Date(r.created_at).toLocaleString('id-ID')}</time></article>`).join('')||'<div class="editor-empty">Belum ada audit event.</div>'}catch(err){el.innerHTML=`<div class="notice error">${esc(err.message)}</div>`}}
$('#refreshAuditBtn').onclick=loadAudit;
boot();
